server:
  port: 8999

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:LongHazard/Config_Server.git
          #          username: LongHazard
          #          password: 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
          clone-on-start: true